apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nodejs-hello-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-nodejs-hello-app
  template:
    metadata:
      labels:
        app: my-nodejs-hello-app
    spec:
      containers:
      - name: my-nodejs-hello-app-container
        image: ankitkumar95/kubesession_123:hellonodejs
        ports:
        - containerPort: 8082
      imagePullSecrets:
      - name: ank-registry-secret
      
---
apiVersion: v1
kind: Service
metadata:
  name: hello-world-nodejs-service
spec:
  selector:
    app: my-nodejs-hello-app-deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8082 
  type: NodePort

